#  Сравнение чисел обусловленности обобщенной матрицы Вандермонда и ее корня

In [34]:
from numpy.linalg import eig, inv, norm, cond
import numpy as np
from tabulate import tabulate

In [2]:
def gen_vandermonde(n):
    result = np.zeros(shape=(n,n))
    for i in range(n):
        for k in range(n):
            result[i,k] = (n-i+1)**(-3*k/2)
    return result

In [3]:
def newton_method(X,epsilon):
    x_k = np.identity(X.shape[0])
    x_k1 = 0.5*(x_k+inv(x_k)@X)
    while norm(x_k1-x_k)>epsilon:
        x_k = x_k1
        x_k1 = 0.5*(x_k+inv(x_k)@X)
    return x_k1

In [9]:
def eig_method(X):
    V = eig(X)[1]
    sigma = np.diag(eig(X)[0]**(0.5))
    return V @ sigma @ inv(V)

Числа обусловленности исходной матрицы X и ее корня B (найденных двумя методами):

In [37]:
conds = []

for i in range(2,11):
    X = gen_vandermonde(i)
    B1 = eig_method(X)
    if i in range(2,8):
        B2 = newton_method(X,1e-3*(i**2))
    else:
        B2 = newton_method(X,1e-2*(i**2))
    conds.append([i,cond(X),cond(B1),cond(B2),norm(B2@B2-X)])

print(tabulate(conds,headers=['n','cond1','cond2','cond3','norm((X - NewtonMeth^2))'],
               tablefmt='github',numalign="right"))

|   n |       cond1 |       cond2 |   cond3 |   norm((X - NewtonMeth^2)) |
|-----|-------------|-------------|---------|----------------------------|
|   2 |     13.3453 |     3.86718 | 3.86713 |                3.38314e-06 |
|   3 |     229.722 |     18.2467 | 18.2467 |                2.04294e-08 |
|   4 |      5529.2 |     110.399 | 110.367 |                2.02704e-06 |
|   5 |      178347 |     837.766 | 819.531 |                 2.2283e-05 |
|   6 | 7.39689e+06 |     7750.36 | 5638.03 |                4.94802e-05 |
|   7 |  3.8161e+08 |     85050.7 | 16563.3 |                8.94198e-05 |
|   8 | 2.38568e+10 | 1.08904e+06 |  189514 |                 0.00988719 |
|   9 | 1.76993e+12 | 1.60532e+07 | 170.493 |                   0.182943 |
|  10 | 1.53207e+14 | 2.82498e+08 | 200.132 |                   0.194734 |


# Приложение:

Обобщенная матрица Вандермонда второго порядка:

In [18]:
X = gen_vandermonde(2)
print(X)

[[1.         0.19245009]
 [1.         0.35355339]]


Корень из обобщенной матрицы Вандермонда второго порядка:

In [19]:
print(eig_method(X))

[[0.9543323  0.13105779]
 [0.68099624 0.51410459]]


Обобщенная матрица Вандермонда третьего порядка:

In [20]:
X = gen_vandermonde(3)
print(X)

[[1.         0.125      0.015625  ]
 [1.         0.19245009 0.03703704]
 [1.         0.35355339 0.125     ]]


Корень из обобщенной матрицы Вандермонда третьего порядка:

In [21]:
print(eig_method(X))

[[0.96050215 0.09518163 0.00861032]
 [0.76960791 0.30780991 0.04918884]
 [0.48582172 0.4970764  0.31042923]]
