#  Сравнение чисел обусловленности обобщенной матрицы Вандермонда и ее корня

In [2]:
from numpy.linalg import eig, inv, norm, cond
import numpy as np
from tabulate import tabulate

In [3]:
def genVandermonde(n):
    result = np.zeros(shape=(n,n))
    for i in range(n):
        for k in range(n):
            result[i,k] = (n-i+1)**(-3*k/2)
    return result

In [4]:
def NewtonMethod(X,epsilon):
    x_k = np.identity(X.shape[0])
    x_k1 = 0.5*(x_k+inv(x_k)@X)
    while norm(x_k1-x_k)>epsilon:
        x_k = x_k1
        x_k1 = 0.5*(x_k+inv(x_k)@X)
    return x_k1

In [5]:
def EigMethod(X):
    V = eig(X)[1]
    sigma = np.diag(eig(X)[0]**(0.5))
    return V @ sigma @ inv(V)

Числа обусловленности исходной матрицы X и ее корня А:

In [6]:
Cond = []

for i in range(2,11):
    X = genVandermonde(i)
    B = EigMethod(X)
    Cond.append([i,cond(X),cond(B)])

print(tabulate(Cond,headers=['n','cond1','cond2'],
               tablefmt='github',numalign="right"))

|   n |       cond1 |       cond2 |
|-----|-------------|-------------|
|   2 |     13.3453 |     3.86718 |
|   3 |     229.722 |     18.2467 |
|   4 |      5529.2 |     110.399 |
|   5 |      178347 |     837.766 |
|   6 | 7.39689e+06 |     7750.36 |
|   7 |  3.8161e+08 |     85050.7 |
|   8 | 2.38568e+10 | 1.08904e+06 |
|   9 | 1.76993e+12 | 1.60532e+07 |
|  10 | 1.53207e+14 | 2.82498e+08 |


# Приложение:

Обобщенная матрица Вандермонда второго порядка:

In [7]:
X = genVandermonde(2)
print(X)

[[1.         0.19245009]
 [1.         0.35355339]]


Корень из обобщенной матрицы Вандермонда второго порядка:

In [8]:
print(EigMethod(X))

[[0.9543323  0.13105779]
 [0.68099624 0.51410459]]


Обобщенная матрица Вандермонда третьего порядка:

In [9]:
X = genVandermonde(3)
print(X)

[[1.         0.125      0.015625  ]
 [1.         0.19245009 0.03703704]
 [1.         0.35355339 0.125     ]]


Корень из обобщенной матрицы Вандермонда третьего порядка:

In [10]:
print(EigMethod(X))

[[0.96050215 0.09518163 0.00861032]
 [0.76960791 0.30780991 0.04918884]
 [0.48582172 0.4970764  0.31042923]]
